### ISSUE TITLE
UI's createTask issue

### ISSUE THREAD

**Issue by nataly-milman** [nataly-milman/os-planner#31]
Task creation activity fails on an emulated Android device:
Pixel 4a API 30
Android 11.0 (Google APIs)

```
    --------- beginning of crash
2021-06-27 21:30:36.353 26779-26779/net.planner.exampleapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: net.planner.exampleapp, PID: 26779
    java.lang.RuntimeException: Unable to start receiver net.planner.exampleapp.WidgetProvider: android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:4101)
        at android.app.ActivityThread.access$1500(ActivityThread.java:246)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1966)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:7876)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

```

**Comment by nataly-milman** [comment]
Edited the wrong one, this one's still an open issue.
